### PR TITLE
Fix missing margin for search box in main menu

### PR DESCRIPTION
**Pull request by stefan-niedermann**
Patch tested with Cinnamon version `5.15.0-53-generic` on `Linux Mint 21 Cinnamon`

| Before | After |
| --- | --- |
| before | after |

### CODE REVIEW

**Comment by Elbullazul** [comment]
can you show how it looks on the vanilla menu too? Just to be sure it doesn't break anything

**Comment by stefan-niedermann** [comment]
Yes, actually the margin issue is present there too and the PR fixes this also for the default menu:

after-default

**Comment by Elbullazul** [comment]
looks good! Thanks for your contribution

**Comment by stefan-niedermann** [comment]
It's a pleasure to contribute this tiny thing to a great project that allows me distributing a sane operating system to casual users without noticing them :smile:

**Comment by stefan-niedermann** [comment]
@smurphos would you mind updating the Cinnamon Spices version this theme so I get this fix distributed in an official way? 🙏 😉

**Pull request merged**
