### PR TITLE
Fix Gnome Shell Status Menu sliders

### PR DESCRIPTION
**Pull request by fishears**
This fixes the color of the sliders in the Status Menu, allowing the slider bar to be seen

### CODE REVIEW

**Comment by fishears** [comment]
Do you mean the problem caused by the size of the user icon? If so then I already have a fix. If not can you explain further what the issue is please?

**Comment by fishears** [comment]
sorry, i didn't know my commits were going to start showing here & I screwed up syncing upstream :p

**Comment by Elbullazul** [comment]
sorry, meant to say to restyle code to match the current document spacing (indentation), but it doesn't matter that much.

**Comment by fishears** [comment]
sorry about my tardy formatting - we got another thing fixed though ;)

**Pull request merged**
